message-api:
  build: ./message-api
  ports:
     - 8081:5000
  volumes:
    - ./message-api:/code
message-generator:
  build: ./message-generator
  volumes:
    - ./message-generator:/code
consumer:
  build: ./consumer
  volumes:
    - ./consumer:/code
www-api:
  build: ./www-api
  ports:
     - 8080:5000
  volumes:
    - ./www-api:/code
www:
  build: ./www
  ports:
    - "9000:9000"
  volumes:
    - ./www:/code
tests:
  build: ./tests
  stdin_open: true
  tty: true
  links:
    - www-api
    - message-api
    - redis
  volumes:
    - ./tests:/code
