producer:
  image: TBD
  restart: always
  stdin_open: true
  tty: true
  links:
  - kafka
consumer:
  image: TBD
  restart: always
  stdin_open: true
  tty: true
  links:
    - kafka
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka:0.9.0.0
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
   - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
