message-api:
  image: TBD
  restart: always
  stdin_open: true
  tty: true
  ports:
   - 5000
  links:
    - kafka
consumer:
  image: TBD
  restart: always
  stdin_open: true
  tty: true
  links:
    - kafka
    - redis
www-api:
  image: TBD
  restart: always
  stdin_open: true
  tty: true
  links:
    - redis
www:
  image: TBD
  restart: always
  tty: true
  stdin_open: true
  ports:
   - 9000
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka:0.9.0.0
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
   - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
redis:
  image: redis
  ports:
   - 6379
